### ISSUE TITLE
Mura 6.0 build url problem

### ISSUE THREAD

**Issue by spills** [stevewithington/MuraFW1#12]
I am running mura 6 (latest) and plugin 3.019 on Railo 4 and iis 7 with URL rewrite enabled to remove index.cfm. When using on a page other than home the build url path is not correct. I can add the component to any page other than home and can see the FW1 default page no problem but when creating another page link `<a href="#buildURL(action='publin:main.newpage')#">New Page</a>` the resulting link will go to site home i.e. http://domain/?MurFW1action=public:main.newpage instead of http://domain/somepage/?MurFW1action=public:main.newpage where FW1 component is.

**Comment by scriptminion** [comment]
This seems like a more appropriate place to post the issue I have.  Please reference my post at https://github.com/stevewithington/MuraFW1/issues/29
