### ISSUE TITLE
Can't Change Subsystems

### ISSUE THREAD

**Issue by chippinkston** [stevewithington/MuraFW1#28]
_Issue Summary:_
Can not change between subsystems in v3.6.

_Background / Expected Behavior:_
I'm in the process of updating some legacy plugins that were using the 2.3x versions of the MuraFW/1 plugin to the v3.6 (current master).  My legacy plugins used a structure of 'public' and 'internal' subsystems - wherein 'internal' would be used for the Add/Edit/Delete/Reporting functions for 'public' displays.  Going to a 'public' listing page as a logged in user would display a link to go to the 'internal' version of the page via "#buildURL('internal:main.default')#". Attempting to reference the link from my public page just reloads the current page, it does not go to the internal subsystem.

_Testing process:_

<ol>
<li>Stand up a new instance of Mura 6.</li>
<li>Download the lastest Master version of the MuraFW/1 plugin (3.6).</li>
<li>Update /includes/fw1config.cfm
<ol>
<li>change package name - variables.framework.package = 'testsubsystems';</li>
<li>change debug mode - variables.framework.debugMode = false;</li>
</li>
<li>Update plugin /app2/views/main/default.cfm - add a new link under the Main header '&lt;a href="#buildURL('app1:main.default')#&gt;App1&lt;/a&gt;'</li>
<li>Install the updated plugin.</li>
<li>Create two pages in Mura.
<ol>
<li>Page 'subPublic' using the plugin's 'MuraFW1 App2' Display Object</li>
<li>Page 'subInternal' using the plugin's 'MuraFW1 App1' Display Object</li>
</li>
<li>Visit page subPublic. - Click the link for 'App1'</li>
<li>The current page should just reload.</li>
</ol>

_Expected Result:_
Would expect the page to display the same results as visiting page 'subInternal'.  Example: Current FW/1 master has an 'Examples as subsystems' demo. 

_Testing Environment:_
- MuraFW/1 Plugin v3.6.
- Mura 6.1 (core: 6.1.6062 / site: 6.1.5294)
- ACF 9.0.2
- Apache 2.2
- Windows 7

**Comment by gpearson** [comment]
What would be the proper way to redirect a user to a new subsystem. I have created a new display object with a Display Method. In the new display method i have the line return getApplication().doAction('siteadmin:main.default');

When a user is logged into the public subsystem and they have a specific group right for the siteadmin suibsystem, I have tried to redirect("siteadmin:main.default") which just displays the public:main.default page. 

Also google has let me down on this or I am not sure what search terms to use.
