### ISSUE TITLE
Add registration link returns to homepage upon clicking.

### ISSUE THREAD

**Issue by romans127** [stevewithington/MuraFW1#29]
I noticed this only happens when index.cfm is in the url. 

I have fixed this by wrapping the link in a conditional that checks if index.cfm is turned on . If so it will render the add registration link with index.cfm within it. 

Is this a viable solution and if so would you like me to submit a pull request.

Ryan.

**Comment by scriptminion** [comment]
I am having an issue not unlike Ryan's
I am using the 62_compat version of the murafw1 with the built in fw 3.1.0 (manual update to 4 would break at plugin install).

index.cfm is ommitted from urls

Running Mura 6.2.6543,ACF 10, Server 2008

Every link takes me back to root when originating url is a few folders deep.
The application.cfc file is the one included in the 62_compat version

Any help would be appreciated.
Thank you,
Chris
