### ISSUE TITLE
eventhandler > fw1/plugin

### ISSUE THREAD

**Issue by fraxen** [stevewithington/MuraFW1#39]
I would like to have a render event direct to an action in a subsystem in the plugin. To make it more clear - I have a _SubType _that we can call _MyClass_ (which is defined in the plugin config file, a subtype to "Page"). Now I would like to have a renderer for this subtype, analgous to the same way that one would do it without a plugin (by creating a dsp_Page_Myclass.cfm in the custom display objects folder), but I would like it to be processed by the Fw1 application.

I have an event defined in eventHandler.cfc:
```javascript
public void function onPageProjectBodyRender($) {
	include '/plugins/amappd/display_objects/dsp_Page_Project.cfm';
}
```

which works, but it is outside the fw1/plugin/application - how can I instead have this call e.g. _subsystem:main.default_

**Comment by fraxen** [comment]
Ah! I got an idea as I was typing this up, and I thought I'd post it here, and leave this issue as it is (maybe you can consider this to the documentation). The trick is to define a _displayobject_ (in the plugin _config.xml.cfm_), then invoke it in the renderer function using _dspObject_. For my example, this works (provided the display object is defined):
```javascript
public void function onPageProjectBodyRender($) {
	writeOutput($.dspObject('plugin' ,'{displayobjectname}');
}
```
where _displayobjectname_ is the name (not the method) that is defined in the _config.xml.cfm_ file.

Voila!

**Comment by fraxen** [comment]
Even better:
```javascript
public void function onPageProjectBodyRender($) {
	writeOutput(getApplication().doAction('subsystem:main.default'))
}
```
Then one doesn't have to define a display object that may not be used in other places!

**Comment by stevewithington** [comment]
Closing as it appears you've figured this out. Feel free to re-open if you need to.
