### ISSUE TITLE
Not Issue - Best Practice Recommendation Requested

### ISSUE THREAD

**Issue by gpearson** [stevewithington/MuraFW1#50]
Looking for recommendations on how to break up a controller that is 5000+ lines of code. Received an issue request on a plugin that uses this as the base template. The controller is for everything that has to deal with an Event. 

Would it be best to use cfinclude and each section of this controller be in a separate file within the controller folder of the sub section or would it be best to create additional functions in another controller and call those functions to make this Events Controller Smaller

**Comment by fraxen** [comment]
Maybe ask this question on the FW1 mailing list? In general, the controller shouldn't have too much logic, you should consider moving things out to service beans, and also to consider setting up sub systems.

**Comment by stevewithington** [comment]
@gpearson I realize this is an old  issue, however as @fraxen has already mentioned, controllers shouldn't have all that much logic in them. It sounds like you may have more service oriented logic in there and possibly need to break things up a bit.
